#!/usr/bin/env bash

VLAD_PATH=`pwd`

cd ~/hacking/jekyll/logaan.github.io/ && \
rm -r vlad

cd ~/hacking/jekyll/logaan.github.io/ && \
cp -R $VLAD_PATH/doc vlad && \
git add . && \
git commit -avm "updated vlad docs" && \
git push origin master
